### PR TITLE
Update design of unconf

### PR DESCRIPTION
**Pull request by bholtbholt**
Yay! New design!

This PR:
- Is mostly CSS changes, with a few class changes to follow BEM-style naming convention
- Themes the app for Polyglot conference (with Polyglot colours)
- Uses CSS custom properties (CSS variables) to make theming the app really easy
- Uses CSS Grid to make the app responsive: 1 column for mobile, more columns as the screen gets wider
- Updated the screenshots

no_pitches
all_votes
schedule

### CODE REVIEW

**Comment by bholtbholt** [comment]
Rebased this with updated master and fixed the [expected] merge conflict from #26.

This PR isn't reliant #27, and can be merged without it 😄

**Comment by kyoung** [comment]
But I liked the clean, white, simple design :laughing:

**Comment by bholtbholt** [comment]
I can change the background colour so it's white -- or re-theme it entirely, it's all really easy to do in https://github.com/kyoung/unconf/pull/28/files#diff-fb5fed966fce63184501ad9ca6181635R29

I thought using Polyglot's theme was nice. And the white cards on the dark background make them stand out more.

Your call! I'm happy to do whatever

**Comment by kyoung** [comment]
No no, too close now :D
I'll get it tested and merged tonight

**Pull request merged**
